### ISSUE TITLE
CentOS 7 dependency issue

### ISSUE THREAD

**Issue by VeryGoodErotica** [w3c/epubcheck#1076]
Tried running on CentOS 7

    java -jar epubcheck.jar --help
    Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Table
            at com.adobe.epubcheck.tool.EpubChecker.<init>(EpubChecker.java:91)
            at com.adobe.epubcheck.tool.Checker.main(Checker.java:30)
    Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Table
            at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            ... 2 more

I do not know much about Java (never really liked it, no offense) but searching it looked like maybe something "Guava" was missing, a `yum list` in CentOS 7 showed a package by that name, but installing it didn't fix the issue.

How do I figure out what is missing so I can install the necessary dependency? And shouldn't the dependencies be listed on the release page? The error message when they aren't there are not very helpful to those of us who are not familiar with Java.

java-1.7.0-openjdk-1.7.0.231-2.6.19.1.el7_6.x86_64
and
java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.x86_64

are both installed (along with "headless" and "devel" packages for both)

**Comment by rdeltour** [comment]
I’m not sure how you installed EPUBCheck, but the issue seems to be that you don’t have its library dependencies.

When you get EPUBCheck from the main ZIP distribution, it comes with all these libraries in a `lib` directory. If you invoke EPUBCheck after having unzipped the distribution (i.e. without moving the main `epubcheck.jar` file to another location) it should work out of the box.

**Comment by VeryGoodErotica** [comment]
I've got this working now.
