### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by laudrain** [w3c/epubcheck#1082]
I have a new macbook and i've had to reinstall all...
I have installed a JRE 8 environnement, and "java -version" gives:
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

Unfortunately, when running EPUBCheck in its folder with the lib folder besides the epubcheck.jar file with the command "java -jar epubcheck.jar", brings immediately the following error message:
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/adobe/epubcheck/tool/Checker : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

What am i doing wrong ?

**Comment by rdeltour** [comment]
> What am i doing wrong ?

Apparently it's the Java installation, since your `java` command returns a version that is below the minimum version required to build EPUBCheck.

Note that you need to install a JDK (Java development kit), not just a JRE (Java runtime environment).

There are various JDK providers; you can download [OpenJDK binaries on adoptopenjdk.net](https://adoptopenjdk.net) , or follow this [guide to install Oracle JDK](https://docs.oracle.com/javase/10/install/installation-jdk-and-jre-macos.htm#JSJIG-GUID-C5F0BF25-3487-4F33-9275-7000C8E1C58C).

**Comment by rdeltour** [comment]
Tagging the issue as `invalid` and closing as it's not an issue with EPUBCheck itself. But feel free to keep on the discussion in the comments!
