### ISSUE TITLE
Could not initialize class com.adobe.epubcheck.ocf.OCFChecker

### ISSUE THREAD

**Issue by Richie94** [w3c/epubcheck#1297]
Hey there,

I got out of nowhere this error, didnt change the version (was 4.2.6)
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.adobe.epubcheck.ocf.OCFChecker
	at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:222)
	at com.adobe.epubcheck.api.EpubCheck.validate(EpubCheck.java:204)
```
Interestingly the problem does not occur in my IntelliJ IDEA (maven 3.8.1), only when I run it with a different local maven version (3.6.3). In our Gitlab Pipeline with DockerImage Maven 3.6.3 and Java 11 it works, in a different gitlab System with same config it does not...
Somehow it worked for me to add also the second dependency, before I had only the first one.
```
<dependency>
    <groupId>org.w3c</groupId>
    <artifactId>epubcheck</artifactId>
    <version>4.2.6</version>
</dependency>

<dependency>
    <groupId>org.idpf</groupId>
    <artifactId>epubcheck</artifactId>
    <version>4.1.1</version>
</dependency>
```
Do you know what could have caused this issue and how I could be able to reset it back to one dependency (btw: what are the differences?)

**Comment by rdeltour** [comment]
It usually happens when EPUBCheck’s dependencies are not found. The solution depends on how you run EPUBCheck. If you're using the default command line distribution, make sure the `lib` directory is next to the main EPUBCheck `.jar` file.

See also answers in the previous issues with [similar questions](https://github.com/w3c/epubcheck/issues?q=is%3Aissue+NoClassDefFoundError).

I'm closing as `invalid` this as this is not a bug with EPUBCheck. But feel free to keep on commenting here, or reopen if you do think there is a bug somewhere.
