### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Matt-1** [w3c/epubcheck#1554]
I have an EPUB for which epubcheck v5.1.0 runs into an error:
```
Validating using EPUB version 3.3 rules.
java.lang.ArrayIndexOutOfBoundsException: 2048
        at org.apache.xerces.impl.io.UTF8Reader.read(Unknown Source)
        at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source)
        at org.apache.xerces.impl.XMLEntityScanner.scanContent(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at com.adobe.epubcheck.xml.XMLParser.process(XMLParser.java:176)
        at com.adobe.epubcheck.ops.OPSChecker.validate(OPSChecker.java:127)
        at com.adobe.epubcheck.ops.OPSChecker.checkContent(OPSChecker.java:97)
        at com.adobe.epubcheck.opf.PublicationResourceChecker.check(PublicationResourceChecker.java:45)
        at com.adobe.epubcheck.opf.OPFChecker.checkItemContent(OPFChecker.java:398)
        at com.adobe.epubcheck.opf.OPFChecker.checkPackage(OPFChecker.java:136)
        at com.adobe.epubcheck.opf.OPFChecker30.checkPackage(OPFChecker30.java:67)
        at com.adobe.epubcheck.opf.OPFChecker.check(OPFChecker.java:94)
        at com.adobe.epubcheck.ocf.OCFChecker.check(OCFChecker.java:173)
        at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:218)
        at com.adobe.epubcheck.tool.EpubChecker.validateFile(EpubChecker.java:250)
        at com.adobe.epubcheck.tool.EpubChecker.processFile(EpubChecker.java:325)
        at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:150)
        at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
```
I cannot publicly share the EPUB but I could email it to you.

**Comment by rdeltour** [comment]
Fixed in #16579
