### ISSUE TITLE
XercesImpl in Classpath is causing EpubCheck failure

### ISSUE THREAD

**Issue by tofi86** [w3c/epubcheck#606]
Having the Xerces Library (i.e. `xercesImpl-2.7.1.jar`) in your Java ClassPath when running EpubCheck, causes EpubCheck to fail with the following error:

```
$> java -cp "epubcheck.jar;xercesImpl-2.7.1.jar;lib/*" com.adobe.epubcheck.tool.Checker "C:\Users\Tobias Fischer\Desktop\4138_epub-kapitelsplit\test.epub"
Verwendung der EPUB 2.0.1 Prüfungen
org.w3c.dom.DOMException: NAMESPACE_ERR: An attempt is made to create or change an object in a way which is incorrect with regard to namespaces.
        at org.apache.xerces.dom.AttrNSImpl.setName(Unknown Source)
        at org.apache.xerces.dom.AttrNSImpl.<init>(Unknown Source)
        at org.apache.xerces.dom.CoreDocumentImpl.createAttributeNS(Unknown Source)
        at org.apache.xerces.dom.ElementImpl.setAttributeNS(Unknown Source)
        at com.adobe.epubcheck.ctc.XmlDocParser$MyHandler.startElement(XmlDocParser.java:209)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at com.adobe.epubcheck.ctc.XmlDocParser.readXML(XmlDocParser.java:134)
        at com.adobe.epubcheck.ctc.XmlDocParser.parseDocument(XmlDocParser.java:61)
        at com.adobe.epubcheck.ctc.PackageReader.getPathToRootFile(PackageReader.java:73)
        at com.adobe.epubcheck.ctc.PackageReader.readPackageData(PackageReader.java:38)
        at com.adobe.epubcheck.ctc.CheckManager.<init>(CheckManager.java:20)
        at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:218)
        at com.adobe.epubcheck.tool.EpubChecker.validateFile(EpubChecker.java:160)
        at com.adobe.epubcheck.tool.EpubChecker.processFile(EpubChecker.java:494)
        at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:254)
        at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
EpubCheck abgeschlossen
```

Whereas EpubCheck doesn't fail without the Xerces library of course:

```
$> java -cp "epubcheck.jar;lib/*" com.adobe.epubcheck.tool.Checker "C:\Users\Tobias Fischer\Desktop\4138_epub-kapitelsplit\test.epub"
Verwendung der EPUB 2.0.1 Prüfungen
WARNING(CSS-017): C:/Users/Tobias Fischer/Desktop/4138_epub-kapitelsplit/test.epub/OEBPS/stylesheet.css(193,17): CSS-Selektor enthält Anweisungen zu absoluter Positionierung.

EpubCheck mit Warnungen abgeschlossen.

EpubCheck abgeschlossen
```

This happens with both Java 7 and 8.

Upgrading XercesImpl to 2.8.1 or 2.9.1 helps and the error is gone, but I stumbled upon this issue as Apache FOP 2.0 still uses 2.7.1 and I have projects where I need to have both libraries in my classpath (epubcheck 4.0.0 and Apache FOP 2.0).

Does anyone have an idea why this is happening? Or how I can prevent this behaviour in my java code? Or what we can do about it in the epubcheck code?

Thanks!

**Comment by rdeltour** [comment]
This rings no bells... however, I note that this is only happening in code from the `ctc` package, not in the parsing made in the other core code. You may want to have a look at how the SAX parser is configured there, and see if the SAX parser or parser factory are configured the same way (e.g. with/without validating, with the same namespace awareness settings, etc).

Also, does it happen systematically or just with some particular EPUB (maybe invalid)?

Let me know if you need further help (although I can't guarantee I'll have a deeper look very soon, this is rather low prio because of the old Xerces version)!

**Comment by tofi86** [comment]
This happens with every EPUB checked when Xerces 2.7.1 is in the ClassPath.

> however, I note that this is only happening in code from the ctc package, not in the parsing made in the other core code.

what does this mean? what is the `ctc` package?

**Comment by rdeltour** [comment]
Closing as inactive. Feel free to reopen if the issue persists with recent version of EPUBCheck.
